# GitHub Sponsors
github: marcos4503

# Platforms of Crowd Funding and Donates
# ko_fi: seu_usuario
# buy_me_a_coffee: seu_usuario
# patreon: seu_usuario

# Custom links for other services
custom: ['https://dub.sh/PayPal-to-marcos4503']