# GitHub Sponsors
github: marcos4503

# Custom links for other services
custom: ['https://dub.sh/PayPal-to-marcos4503']

# Standard platforms of Crowd Funding and Donates
# patreon: seu_usuario
# ko_fi: marcos4503
buy_me_a_coffee: marcos4503