name: "🛟 Support or Help Request"
description: "Need help, have questions or facing difficulties with the Product?"
title: "[SUPPORT] - "
labels: ["help wanted", "question"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.
        
        ### 👋 Welcome to Support!
        **Before opening the request**, please **check the existing open/closed Issues** or Documentation/ReadMe (if applicable), to see if your question has already been answered. **Provide as much detail as possible** so we can assist you efficiently.

  - type: textarea
    id: description
    attributes:
      label: "Support Details"
      description: "What do you need help with? Describe the problem or what you need support with."
      placeholder: "I'm having a problem with..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Extra Context"
      description: "Enter additional info, if necessary, such as Product version, Logs, running Environment/Platform/OS, etc."
      placeholder: |
        I'm using Product v1.0.0 on Windows 11...
        (For Log Files or Config/Text Files, attach below)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checks"
      options:
        - label: "I have checked the existing Issues. My request is not answered there."
          required: true