name: "🐞 Bug Report"
description: "Report a reproducible bug, error, glitch, or unexpected behavior in the Product."
title: "[BUG] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.

        ### ⭐ Thank you for your help!
        Before submitting this report, please **ensure the bug is reproducible** in the latest version of the Product. Clear steps and details help fix the issue much faster.

  - type: textarea
    id: description
    attributes:
      label: "Bug Details"
      description: "What is happening? What was the expected behavior? Enter a clear and concise description of what the bug is."
      placeholder: "Something is happening that shouldn't be happening..."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "How do we make it happen? Tell exactly how to trigger the bug. Numbered steps are highly appreciated! :)"
      placeholder: |
        1. Open the '...'
        2. Click on '...'
        3. Do '...'
        4. See the error/bug '...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Extra Context"
      description: "Enter additional info, such as Logs, running Environment/Platform/OS, Project version, etc."
      placeholder: "Using Project v1.0.0, Windows 11, Using Project together with '...' software..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checks"
      options:
        - label: "I'm using the latest version of the Project/Software and this bug is reproducible."
          required: true