name: "🏗️ Code Change Proposal"
description: "Start a discussion as a Contributor, to propose a Code Change that you want to make to the Product."
title: "[CODE] - "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.

        ### 🌱 Thank you for helping the project evolve!
        If you are a existing or a new **contributor** wanting to propose a **code change**, this is the place. Open this Issue to discuss the **code change** that you want to implement in the Product. Please be as detailed as possible, this helps us to better understand the proposal and how it will be implemented. :)

  - type: textarea
    id: change_details
    attributes:
      label: "Code Change Details"
      description: "Describe the code change. Why is it needed? How should it be implemented?"
      placeholder: "I propose implementing/changing/refactoring..."
    validations:
      required: true