name: "🏗️ Code Change Proposal"
description: "Start a discussion as a Contributor, to propose a Code Change that you want to make to the Product."
title: "[CODE] - "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.

        ### 🌱 Thank you for helping the project evolve!
        If you are a existing or a new **Contributor** wanting to propose a **Code Change**, this is the place. Open this Issue to discuss the **Code Change** that you want to implement in the Product.

        - After discussing here, you can create a **new Branch** on this Repository (**or, if you're external**, Fork it to your account, then open a **new Branch**).
        - After implementing the change in the new Branch, **open a Pull Request** referencing this Issue, to bring the change, officially, to the Product.
        
        Please be as detailed as possible, this helps us to better understand the proposal and how it will be implemented. :)

  - type: textarea
    id: change_details
    attributes:
      label: "Code Change Details"
      description: "Describe the Code Change. Why is it needed? What will be implemented? How should it be implemented?"
      placeholder: "I propose implementing/changing/refactoring..."
    validations:
      required: true