name: "💡 Feature, Improve or Change Proposal"
description: "Suggest a new feature, improvement, idea or a code change proposal for the software/project."
title: "[Proposal] - "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.

        ### 🌱 Thank you for helping the project evolve!
        Whether you are a **user** with a great suggestion or a **contributor** wanting to propose a **code change**, this is the place. Please be as detailed as possible, this helps us to better understand the proposal and how to implement it. :)

  - type: dropdown
    id: request_type
    attributes:
      label: "Profile"
      description: "Are you suggesting a feedback as a regular user OR a technical change as a contributor?"
      options:
        - "☕ User: I have an Suggestion"
        - "🏗️ Contributor: Code Change Proposal"
    validations:
      required: true

  - type: textarea
    id: feature_details
    attributes:
      label: "Proposal Details"
      description: "Describe your suggesting or change. Why is it needed? How should it work? (For proposal of code change, mention implementation details)"
      placeholder: "I suggest that... OR I propose refactoring the..."
    validations:
      required: true