name: "💡 Feature, Improve or Change Proposal"
description: "Suggest a new feature, improvement, idea or a code change proposal for the software/project."
title: "[Proposal] - "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.

        ### 🌱 Thank you for helping the project evolve!
        Whether you are a **user** with a great suggestion or a **contributor** wanting to propose a **code change**, this is the place. Please be as detailed as possible.

  - type: dropdown
    id: request_type
    attributes:
      label: "Profile"
      description: "Are you suggesting a feedback as a user OR a technical change as a contributor?"
      options:
        - "☕ User: I have an Suggestion"
        - "🏗️ Contributor: I'ma propose a Code Change"
    validations:
      required: true

  - type: textarea
    id: feature_details
    attributes:
      label: "Proposal Details"
      description: "Describe your suggesting or change. Why is it needed? How should it work? (If proposing code, mention implementation details)."
      placeholder: "I suggest that... OR I propose refactoring the..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checks"
      options:
        - label: "I have checked the existing Issues and my proposal is unique."
          required: true