name: "🛟 Support or Help Request"
description: "Need help, have questions, or facing difficulties with the project/software?"
title: "[Support] - "
labels: ["help wanted", "question"]
body:
  - type: markdown
    attributes:
      value: |
        > Don't delete the Tag. Try creating a descriptive title, but not an excessively long one.
        ### 👋 Welcome to Support!
        **Before opening the request**, please **check the existing open/closed Issues** or Documentation/ReadMe (if applicable), to see if your question has already been answered. **Provide as much detail as possible** so we can assist you efficiently.

  - type: textarea
    id: description
    attributes:
      label: "Support Details"
      description: "What do you need help with? Describe the problem or what you need help/support with."
      placeholder: "I'm having a problem with..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Extra Context"
      description: "Enter additional info, if necessary, such as Logs, running Environment/Platform/OS, Project version, etc."
      placeholder: "Using Project v1.0.0, Windows 11, Log Output: ..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checks"
      options:
        - label: "I have checked the existing Issues. My request is not answered there."
          required: true