name: "🛟 Support or Help Request"
description: "Need help, have questions, or facing difficulties with the project or software?"
title: "[Support] - "
labels: ["help wanted", "question"]
body:
  - type: markdown
    attributes:
      value: |
        > a
        ### 👋 Welcome to Support!
        **Before opening the request**, please **check the existing closed Issues** or Documentation/ReadMe/FAQs (if applicable), to see if your question has already been answered. **Provide as much detail as possible** so we can assist you efficiently.

  - type: textarea
    id: description
    attributes:
      label: "What do you need help with?"
      description: "Please describe the problem or what you need help or support with, providing as much detail as possible."
      placeholder: "I'm having a problem with..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context and Environment"
      description: "Are there any specific logs, versions, OS details, or error messages that might help us understand the situation?"
      placeholder: "Windows 11, using Smart Branch Switch v1.0.0. Terminal log output: ..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Before submitting"
      options:
        - label: "I have checked the documentation and existing issues, and my question is not answered there."
          required: true
        - label: "I understand that this is a public repository and any data shared here will be visible to everyone."
          required: true